### ISSUE TITLE
Programmatically enable selection mode

### ISSUE THREAD

**Issue by StefanOltmann** [jordond/drag-select-compose#43]
Aside from the selection mode activation on long-press, my app also includes a dedicated button for this purpose, similar to Apple Photos. This design choice is based on the fact that Android users are accustomed to the long press, while iOS users expect a separate button for enabling the selection mode.

To enhance user experience, I would like to propose the addition of a function called dragSelectState.enableSelectionMode() or a similar method. This feature would provide a convenient way for users to activate the selection mode, regardless of their preferred method (long-press or button).

Of course it is essential to maintain the behavior of automatically ending the selection mode when the last photo is deselected.

<img width="922" alt="screenshot_1" src="https://github.com/jordond/drag-select-compose/assets/9299303/f2c4e7dd-0a28-4563-a636-5446a1b4f7f3">

<img width="922" alt="screenshot_2" src="https://github.com/jordond/drag-select-compose/assets/9299303/8f3c1c51-7644-4612-a57c-fd111517f9e1">

**Comment by jordond** [comment]
Great idea!  As a android user I had no idea about iOS not really utilizing long presses.

**Comment by StefanOltmann** [comment]
Very nice 👍
