### ISSUE TITLE
min sdk 21

### ISSUE THREAD

**Issue by T8RIN** [jordond/drag-select-compose#86]
Why it is need to use min 26 ? Could you set it to 21, please ? 👀

**Comment by jordond** [comment]
Looks like releases are timing out, so this will get released tomorrow.

**Comment by T8RIN** [comment]
Thanks :)

**Comment by T8RIN** [comment]
![image](https://github.com/jordond/drag-select-compose/assets/52178347/87bb5ac1-87c8-492e-87ea-5299f47c7744)

**Comment by jordond** [comment]
MavenCentral was having issues last night, so I was unable to release until this morning.
